ci: Temporarily disable armebv8 test
```
2443 sigaltstack(0x40ffe9cc,(nil)) = 0
2443 rt_sigaction(SIGSEGV,0x40ffe8e8,NULL) = 0
2443 rt_sigaction(SIGBUS,NULL,0x40ffe974) = 0
2443 rt_sigaction(SIGBUS,0x40ffe8e8,NULL) = 0
2443 ioctl(1,TCGETS,0x40ffe1fc) = -1 errno=25 (Inappropriate ioctl for device)
--- SIGSEGV {si_signo=SIGSEGV, si_code=1, si_addr=0x00000005} ---
2443 rt_sigaction(SIGSEGV,0x4102f8c0,NULL) = 0
2443 rt_sigreturn((nil)) = -1 errno=513 (Successful exit from sigreturn)
--- SIGSEGV {si_signo=SIGSEGV, si_code=1, si_addr=0x00000005} ---
qemu: uncaught target signal 11 (Segmentation fault) - core dumped
error: test failed, to rerun pass `--bin rust-test`

Caused by:
  process didn't exit successfully: `qemu-armeb /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/armeb-unknown-linux-gnueabi/debug/deps/rust_test-91689bb4d013509e` (signal: 11, SIGSEGV: invalid memory reference)
```