ci: Temporarily disable mips r6 test
```
     Running `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name addr2line --edition=2018 /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/addr2line-0.25.1/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="alloc"' --cfg 'feature="core"' --cfg 'feature="rustc-dep-of-std"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("all", "alloc", "bin", "cargo-all", "core", "cpp_demangle", "default", "fallible-iterator", "loader", "rustc-demangle", "rustc-dep-of-std", "smallvec", "std", "wasm"))' -C metadata=95eb00848116bde7 -C extra-filename=-80ec965187532e36 --out-dir /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps --target mipsisa64r6-unknown-linux-gnuabi64 -C linker=mipsisa64r6-linux-gnuabi64-gcc -Z force-unstable-if-unmarked -L dependency=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps -L dependency=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/debug/deps --extern gimli=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libgimli-cabcbf9ed5ddb4c5.rmeta --extern alloc=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/librustc_std_workspace_alloc-8d78143629c25c64.rmeta --extern core=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/librustc_std_workspace_core-6182d033b489b0da.rmeta --cap-lints allow -D warnings`
error: rustc interrupted by SIGILL, printing backtrace

/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-1c4195dec9454671.so(+0x3c2170c)[0x7fb9e8c2170c]
/lib/x86_64-linux-gnu/libc.so.6(+0x45330)[0x7fb9e4c45330]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM.so.22.1-rust-1.95.0-nightly(+0x7b23d1c)[0x7fb9e1d23d1c]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM.so.22.1-rust-1.95.0-nightly(_ZN4llvm10AsmPrinter16emitFunctionBodyEv+0xd29)[0x7fb9e355f1ef]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM.so.22.1-rust-1.95.0-nightly(+0x7b22dd0)[0x7fb9e1d22dd0]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM.so.22.1-rust-1.95.0-nightly(_ZN4llvm13FPPassManager13runOnFunctionERNS_8FunctionE+0x8db)[0x7fb9e2c2845b]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM.so.22.1-rust-1.95.0-nightly(_ZN4llvm13FPPassManager11runOnModuleERNS_6ModuleE+0x28)[0x7fb9e2c27abe]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/libLLVM.so.22.1-rust-1.95.0-nightly(_ZN4llvm6legacy15PassManagerImpl3runERNS_6ModuleE+0x2b0)[0x7fb9e32000c6]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-1c4195dec9454671.so(+0x62ae505)[0x7fb9eb2ae505]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-1c4195dec9454671.so(+0x62adf80)[0x7fb9eb2adf80]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-1c4195dec9454671.so(_RNvXs1_Cs8aadR8nDtV_18rustc_codegen_llvmNtB5_18LlvmCodegenBackendNtNtNtCs7MfJHGoPxZX_17rustc_codegen_ssa6traits5write19WriteBackendMethods7codegen+0x4eb)[0x7fb9eb2af7ad]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-1c4195dec9454671.so(_RINvNtNtCsjJKIREQhhHv_3std3sys9backtrace28___rust_begin_short_backtraceNCINvXs0_Cs8aadR8nDtV_18rustc_codegen_llvmNtB1g_18LlvmCodegenBackendNtNtNtCs7MfJHGoPxZX_17rustc_codegen_ssa6traits7backend19ExtraBackendMethods18spawn_named_threadNCINvNtNtB2j_4back5write10spawn_workB1N_E0uE0uEB1g_+0x1f5)[0x7fb9eb428d85]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-1c4195dec9454671.so(+0x6428902)[0x7fb9eb428902]
/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/librustc_driver-1c4195dec9454671.so(+0x642c26c)[0x7fb9eb42c26c]
/lib/x86_64-linux-gnu/libc.so.6(+0x9caa4)[0x7fb9e4c9caa4]
/lib/x86_64-linux-gnu/libc.so.6(+0x129c6c)[0x7fb9e4d29c6c]

note: we would appreciate a report at https://github.com/rust-lang/rust
     Running `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name std --edition=2024 /home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/std/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type rlib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --warn=unexpected_cfgs --check-cfg 'cfg(feature, values(any()))' --check-cfg 'cfg(target_has_reliable_f16)' --check-cfg 'cfg(target_has_reliable_f16_math)' --check-cfg 'cfg(target_has_reliable_f128)' --check-cfg 'cfg(target_has_reliable_f128_math)' --cfg 'feature="addr2line"' --cfg 'feature="backtrace"' --cfg 'feature="miniz_oxide"' --cfg 'feature="object"' --cfg 'feature="panic-unwind"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("addr2line", "backtrace", "backtrace-trace-only", "compiler-builtins-c", "compiler-builtins-mem", "compiler-builtins-no-f16-f128", "debug_refcell", "llvm-libunwind", "llvm_enzyme", "miniz_oxide", "object", "optimize_for_size", "panic-unwind", "system-llvm-libunwind", "windows_raw_dylib"))' -C metadata=e699a8a386320edb -C extra-filename=-53c621da3a53acc2 --out-dir /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps --target mipsisa64r6-unknown-linux-gnuabi64 -C linker=mipsisa64r6-linux-gnuabi64-gcc -Z force-unstable-if-unmarked -L dependency=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps -L dependency=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/debug/deps --extern 'priv:addr2line=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libaddr2line-80ec965187532e36.rmeta' --extern alloc=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/liballoc-7db865e79b501c29.rmeta --extern 'priv:cfg_if=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libcfg_if-0746eb82d784a330.rmeta' --extern core=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libcore-cd428d78750e97e4.rmeta --extern 'priv:hashbrown=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libhashbrown-38a78ae43d9b59f5.rmeta' --extern libc=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/liblibc-91f4cf418429aec8.rmeta --extern 'priv:miniz_oxide=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libminiz_oxide-d0d0ca68d8934a7c.rmeta' --extern 'priv:object=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libobject-45d6027c4bcb02d8.rmeta' --extern 'priv:panic_abort=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libpanic_abort-4cdd009db1e66b38.rmeta' --extern 'priv:panic_unwind=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libpanic_unwind-f421240014ede54b.rmeta' --extern 'priv:rustc_demangle=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/librustc_demangle-d41279c6867b05a9.rmeta' --extern std_detect=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libstd_detect-789cf67afcc5b376.rmeta --extern 'priv:unwind=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/libunwind-0e3e1f25b102d143.rmeta' -Z unstable-options --cap-lints allow -D warnings --cfg backtrace_in_libstd --check-cfg 'cfg(netbsd10)' --check-cfg 'cfg(no_global_oom_handling)' --check-cfg 'cfg(restricted_std)' --check-cfg 'cfg(backtrace_in_libstd)'`
error: could not compile `gimli` (lib)

Caused by:
  process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name gimli --edition=2018 /home/runner/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/gimli-0.32.3/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type lib --emit=dep-info,metadata,link -C embed-bitcode=no -C debuginfo=2 --cfg 'feature="read"' --cfg 'feature="read-core"' --cfg 'feature="rustc-dep-of-std"' --check-cfg 'cfg(docsrs,test)' --check-cfg 'cfg(feature, values("default", "endian-reader", "fallible-iterator", "read", "read-all", "read-core", "rustc-dep-of-std", "std", "write"))' -C metadata=0225e5ac6b554986 -C extra-filename=-cabcbf9ed5ddb4c5 --out-dir /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps --target mipsisa64r6-unknown-linux-gnuabi64 -C linker=mipsisa64r6-linux-gnuabi64-gcc -Z force-unstable-if-unmarked -L dependency=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps -L dependency=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/debug/deps --extern alloc=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/librustc_std_workspace_alloc-8d78143629c25c64.rmeta --extern core=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/mipsisa64r6-unknown-linux-gnuabi64/debug/deps/librustc_std_workspace_core-6182d033b489b0da.rmeta --cap-lints allow -D warnings` (signal: 4, SIGILL: illegal instruction)
warning: build failed, waiting for other jobs to finish...
```