ci: Temporarily disable wasm32-wasip1-threads test
```
     Running `wasm32-wasip1-threads-runner /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/wasm32-wasip1-threads/debug/deps/rust_test-9521e4a02c112c0a.wasm`
memory allocation of 1664 bytes failed
Error: failed to run main module `/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/wasm32-wasip1-threads/debug/deps/rust_test-9521e4a02c112c0a.wasm`

Caused by:
    0: failed to invoke command default
    1: error while executing at wasm backtrace:
           0:   0x3168 - rust_test-9521e4a02c112c0a.wasm!abort
           1:  0x4b676 - rust_test-9521e4a02c112c0a.wasm!std::sys::pal::wasip1::helpers::abort_internal::h8f78f5f77b447842
           2:  0x4649d - rust_test-9521e4a02c112c0a.wasm!std::process::abort::h4029e5221ea2d6c6
           3:  0x466fa - rust_test-9521e4a02c112c0a.wasm!std::alloc::rust_oom::hcfd0604dee5ebb3a
           4:  0x466ca - rust_test-9521e4a02c112c0a.wasm!__rustc::__rg_oom
           5:   0x23ad - rust_test-9521e4a02c112c0a.wasm!__rustc::__rust_alloc_error_handler
           6:  0x52fd4 - rust_test-9521e4a02c112c0a.wasm!alloc::alloc::handle_alloc_error::h83e22874cfca0a6d
           7:  0x52c9e - rust_test-9521e4a02c112c0a.wasm!alloc::raw_vec::handle_error::h718c02d3faf9c047
           8:  0x3fa3f - rust_test-9521e4a02c112c0a.wasm!alloc::raw_vec::RawVec$LT$T$C$A$GT$::grow_one::hb751d7336aa1f2e8
           9:  0x40e4d - rust_test-9521e4a02c112c0a.wasm!getopts::Options::optflag::hcc9c37f7e595b52e
          10:  0x2a66e - rust_test-9521e4a02c112c0a.wasm!test::cli::optgroups::h9ff1fe349e9b1538
          11:  0x27305 - rust_test-9521e4a02c112c0a.wasm!test::cli::parse_opts::hbeb2821b7d0cf9cb
          12:  0x26ad4 - rust_test-9521e4a02c112c0a.wasm!test::test_main::hd657f36bc63cbb2f
          13:  0x26a45 - rust_test-9521e4a02c112c0a.wasm!test::test_main_static::h26d21d5f3bd099f2
          14:   0x21ed - rust_test-9521e4a02c112c0a.wasm!rust_test::main::h917aac5bec8a04a0
          15:    0xc2c - rust_test-9521e4a02c112c0a.wasm!core::ops::function::FnOnce::call_once::h29c411855a310c4a
          16:    0xbe9 - rust_test-9521e4a02c112c0a.wasm!std::sys::backtrace::__rust_begin_short_backtrace::h140aea0653b87e67
          17:    0xb9d - rust_test-9521e4a02c112c0a.wasm!std::rt::lang_start::_$u7b$$u7b$closure$u7d$$u7d$::h67dd59c45fc9d53d
          18:  0x49c2a - rust_test-9521e4a02c112c0a.wasm!std::rt::lang_start_internal::h59ddbce5f71c9fe1
          19:    0xb63 - rust_test-9521e4a02c112c0a.wasm!std::rt::lang_start::h4e6862d3d870ca0a
          20:   0x2361 - rust_test-9521e4a02c112c0a.wasm!__main_void
          21:    0xaf8 - rust_test-9521e4a02c112c0a.wasm!_start
       note: using the `WASMTIME_BACKTRACE_DETAILS=1` environment variable may show more debugging information
    2: wasm trap: wasm `unreachable` instruction executed

Stack backtrace:
   0: anyhow::error::<impl core::convert::From<E> for anyhow::Error>::from
error: test failed, to rerun pass `--bin rust-test`

Caused by:
  process didn't exit successfully: `wasm32-wasip1-threads-runner /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/wasm32-wasip1-threads/debug/deps/rust_test-9521e4a02c112c0a.wasm` (exit status: 134)
```