ci: Temporarily disable 32-bit sparc build
```
error: linking with `sparc-unknown-linux-gnu-gcc` failed: exit status: 1
  |
  = note: LC_ALL="C" PATH="/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/bin:/snap/bin:/home/runner/.local/bin:/opt/pipx_bin:/home/runner/.cargo/bin:/home/runner/.config/composer/vendor/bin:/usr/local/.ghcup/bin:/home/runner/.dotnet/tools:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin" VSLANG="1033" "sparc-unknown-linux-gnu-gcc" "/tmp/rustc7pun9g/symbols.o" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.2nax0l25bozdyyszhbz3b13p7.rcgu.o" "-Wl,--as-needed" "-Wl,-Bstatic" "-lhello_c" "-Wl,-Bdynamic" "-lc" "-Wl,-Bstatic" "-lhello_cpp" "-Wl,-Bdynamic" "-lstdc++" "-Wl,-Bstatic" "-lhello_cmake" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libstd-d11f682b4bcd0d25.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libpanic_unwind-b9d7a9dd1623fc32.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libobject-3f3cfab437eaaee4.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libmemchr-5622310b692c8d3e.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libaddr2line-2d7e5688d108464e.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libgimli-9eb36785fcd4507a.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/librustc_demangle-07199249b10731dd.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libstd_detect-aec7868cb972e3dc.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libhashbrown-efb7621ea279fa0a.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/librustc_std_workspace_alloc-cf5b25500f3f11e2.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libminiz_oxide-1eab108422226b9a.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libadler-a5eb3139e2f5c7ac.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libunwind-46475d4b0cb11fdb.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libcfg_if-c8fdeb2850ab952e.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/liblibc-34d315da02cd1898.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/liballoc-315da8cdb1b99647.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/librustc_std_workspace_core-c75815d2d78a73eb.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libcore-dc64dfd5f853deed.rlib" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libcompiler_builtins-bc558a2a34d12de1.rlib" "-Wl,-Bdynamic" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-mcpu=v9" "-m32" "-Wl,--eh-frame-hdr" "-Wl,-z,noexecstack" "-L" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/build/rust-test-2114d6623600f1c4/out" "-L" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/build/rust-test-2114d6623600f1c4/out" "-L" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/build/rust-test-2114d6623600f1c4/out" "-L" "/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/sparc-unknown-linux-gnu/lib" "-o" "/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e" "-Wl,--gc-sections" "-pie" "-Wl,-z,relro,-z,now" "-Wl,-O1" "-Wl,--strip-debug" "-nodefaultlibs"
  = note: /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: relocations in generic ELF (EM: 18)
          /usr/lib/gcc-cross/sparc64-linux-gnu/11/../../../../sparc64-linux-gnu/bin/ld: /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/rust_test-0bc9c87693f6ae1e.rust_test.c7716ebdceddcedf-cgu.0.rcgu.o: error adding symbols: file in wrong format
          collect2: error: ld returned 1 exit status

error: could not compile `rust-test` (bin "rust-test") due to 1 previous error

Caused by:
  process didn't exit successfully: `/home/runner/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/bin/rustc --crate-name rust_test --edition=2021 docker/test/fixtures/rust/src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C embed-bitcode=no --warn=unsafe_op_in_unsafe_fn --warn=single_use_lifetimes --warn=rust_2018_idioms --cfg 'feature="cpp"' --cfg 'feature="default"' --check-cfg 'cfg(docsrs)' --check-cfg 'cfg(feature, values("cpp", "default"))' -C metadata=0bc9c87693f6ae1e -C extra-filename=-0bc9c87693f6ae1e --out-dir /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps --target sparc-unknown-linux-gnu -C linker=sparc-unknown-linux-gnu-gcc -C strip=debuginfo -L dependency=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps -L dependency=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/release/deps --extern 'noprelude:alloc=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/liballoc-315da8cdb1b99647.rlib' --extern 'noprelude:compiler_builtins=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libcompiler_builtins-bc558a2a34d12de1.rlib' --extern 'noprelude:core=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libcore-dc64dfd5f853deed.rlib' --extern 'noprelude:panic_unwind=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libpanic_unwind-b9d7a9dd1623fc32.rlib' --extern 'noprelude:proc_macro=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libproc_macro-fd1f9588f62f5367.rlib' --extern 'noprelude:std=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/deps/libstd-d11f682b4bcd0d25.rlib' -Z unstable-options -D warnings -L native=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/build/rust-test-2114d6623600f1c4/out -L native=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/build/rust-test-2114d6623600f1c4/out -L native=/home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/release/build/rust-test-2114d6623600f1c4/out -l static=hello_c -l c -l static=hello_cpp -l stdc++ -l static=hello_cmake --check-cfg 'cfg(no_c,no_cmake)'` (exit status: 1)
```