ci: Disable 32-bit sparc with debug mode due to stack overflow
```
test tests::test ... Hello C from Rust!
Hello C++ from Rust!
3938 futex(0x7839502c,FUTEX_PRIVATE_FLAG|FUTEX_WAKE,1,0x00000002,0x710fdbf8,1896864760) = 1
 = 0
3938 futex(0x717f3ba8,FUTEX_CLOCK_REALTIME|FUTEX_WAIT_BITSET,3940,NULL,NULL,0)3938 sigaltstack(0x717f3130,(nil)) = 0
3938 munmap(0x714c8000,24576) = 0
3938 rt_sigprocmask(SIG_BLOCK,0x717f3fb4,NULL,8) = 0
3938 madvise(0x715f2000,2072576,MADV_DONTNEED) = 0
3938 exit(0)
 = 0
3938 write(1,0x78395ca0,2) = 2
3938 write(1,0x782b4caa,1) = 1
ok
3938 clock_gettime64(CLOCK_MONOTONIC,0x70ffea00) = 0 ({tv_sec=364,tv_nsec=255580580})
3938 write(1,0x782b4ece,1) = 1

3938 write(1,0x78395ca0,13) = 13
3938 write(1,0x78395ca0,2) = 2
3938 write(1,0x78395ca0,59) = 59
--- SIGSEGV {si_signo=SIGSEGV, si_code=2, si_addr=0x70001fd0} ---
3938 write(2,0x782bfdc2,9)
thread ' = 9
3938 write(2,0x782c14a4,4)main = 4
3938 write(2,0x782bfdcb,27)' has overflowed its stack
 = 27
3938 write(2,0x782bfdef,36)fatal runtime error: stack overflow
 = 36
3938 rt_sigprocmask(SIG_UNBLOCK,0x7104f9a8,NULL,8) = 0
3938 gettid() = 3938
3938 getpid() = 3938
3938 tgkill(3938,3938,SIGIOT) = 0
--- SIGIOT {si_signo=SIGIOT, si_code=SI_TKILL, si_pid=3938, si_uid=1001} ---
error: test failed, to rerun pass `--bin rust-test`

Caused by:
  process didn't exit successfully: `qemu-sparc32plus /home/runner/work/setup-cross-toolchain-action/setup-cross-toolchain-action/rust-cross-toolchain/target/sparc-unknown-linux-gnu/debug/deps/rust_test-2630a9a8f3ff73f6` (signal: 6, SIGABRT: process abort signal)
```